### ISSUE TITLE
How does the script work?

### ISSUE THREAD

**Issue by HenryPD96** [giacomomarchioro/PyEnergyDiagrams#2]
Hi,

I am unsure how I need to edit this script it to work? Which bit is code and which isn't in the .py file?

Thank you,

Henry

**Comment by giacomomarchioro** [comment]
Hi Henry, 
if you are editing directly the script just edit the code written below:

__name__ == “__main__"

Otherwise if you are using it as a module just import it (putting it in your python path) or in the same folder of your script and then follow the example. 

Let me know if you need help, 

Giacomo

**Comment by HenryPD96** [comment]
I am not sure where in the .py the necessary code starts? Apologies I am an undergraduate student doing Chemistry and need this to work to include in a publication. 

Could you help me by showing an example please?

Thank you in advance,

Henry
